[colors.bright]
black = "#686868"
blue = "#59C2FF"
cyan = "#95E6CB"
green = "#C2D94C"
magenta = "#FFEE99"
red = "#F07178"
white = "#FFFFFF"
yellow = "#FFB454"

[colors.normal]
black = "#01060E"
blue = "#53BDFA"
cyan = "#90E1C6"
green = "#91B362"
magenta = "#FAE994"
red = "#EA6C73"
white = "#C7C7C7"
yellow = "#F9AF4F"

[colors.primary]
background = "#0A0E14"
foreground = "#B3B1AD"

[cursor.style]
blinking = "On"
shape = "Beam"

[font]
size = 14

[font.bold]
family = "Hurmit Nerd Font Mono"
style = "bold"

[font.normal]
family = "Hurmit Nerd Font Mono"
style = "Regular"

[terminal.shell]
args = ["-l", "-c", "tmux attach || tmux"]
program = "/bin/zsh"

[window]
decorations = "none"
startup_mode = "Maximized"

[terminal]
